### ISSUE TITLE
Allow generating on `view-source:` URI schema.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ichaoX/ext-textFragment#11]
As an example, [`view-source:https://gitlab.gnome.org/#:~:text=Error%20503%20All,Varnish%20cache%20server`](view-source:https://gitlab.gnome.org/#:~:text=Error%20503%20All,Varnish%20cache%20server) (from the `cite=` field of the `<blockQuote>` at https://discourse.gnome.org/t/unable-to-access-gitlab-gnome-org/24554?u=rokejulianlockhart) highlights the correct text:

> ![image](https://github.com/user-attachments/assets/b7d8e505-4bf1-40d5-9dd8-98aba88d9c85)

...yet I'm unable to generate the URI in that GUI - instead, I must generate it on the `https` version, and hope that the text is verbatim in the source (which isn't true when JS is involved, of course).

**Comment by ichaoX** [comment]
This issue is the same as the reason for https://github.com/ichaoX/ext-textFragment/issues/5#issuecomment-2217746215 .

After 538cd92efa468f4ac32faeb5b0ab3b93429f8a11, it will be possible to copy, but due to the lack of context retrieval functionality, features like creating links and finding text fragments will still be degraded.

**Comment by RokeJulianLockhart** [comment]
@ichaoX, I presume that means it isn't possible to remediate, then. I'll close. Thanks anyway.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ichaoX/ext-textFragment/issues/11#event-14732122535

@ichaoX, am I correct to interpret that PR as permitting the extension to *generate* fragment directives in the GUI that Firefox provides for the `view-source` schema?

**Comment by ichaoX** [comment]
> > [#11 (comment)](https://github.com/ichaoX/ext-textFragment/issues/11#event-14732122535)
> 
> @ichaoX, am I correct to interpret that PR as permitting the extension to _generate_ fragment directives in the GUI that Firefox provides for the `view-source` schema?

Improved the implementation of writing to the clipboard, as mentioned in https://github.com/ichaoX/ext-textFragment/issues/11#issuecomment-2418461451 ; it has been downgraded but is basically usable.

**Comment by RokeJulianLockhart** [comment]
This functionality works now! Many thanks.
