### ISSUE TITLE
Custom Extension Shortcuts

### ISSUE THREAD

**Issue by TranquilMind97** [ichaoX/ext-textFragment#12]
Greetings, Love this extension & Nice Work. 👍

Is it possible to add a custom keyboard shortcut feature that can copy the link to the text fragment? Would be nice if for example we can assign Ctrl + Alt + C to achieve this instead of right-clicking for the context menu options.

Thank you.

**Comment by ichaoX** [comment]
The basic shortcut feature will be added in the next update.

Manage shortcuts: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
