### ISSUE TITLE
Provide option to operate on Firefox's `extensions.webextensions.restrictedDomains` entries.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ichaoX/ext-textFragment#5]
As https://github.com/gildas-lormeau/SingleFile/issues/1494#issue-2395597545 states:

> Although https://github.com/gildas-lormeau/SingleFile/blob/14da84df6dd3191b31f45c6ecb1dc5c721eea090/faq.md#why-cant-i-save-some-pages-like-httpsaddonsmozillaorgaddonsingle-file states:
> 
> > For security purposes, browsers block web extensions on certain domains. This prevents a malicious extension to remove or change bad reviews, for example.
> 
> This is bypassable now. As https://superuser.com/questions/1354603/firefox-extensions-restricted-from-running-on-some-sites#comment2926608_1354612 explains, https://support.mozilla.org/en-US/kb/quarantined-domains?as=u&utm_source=inproduct#:~:text=how%20can%20i%20re-enable%20the%20add-ons%20that%20are%20not%20allowed%20on%20sites%20restricted%20by%20mozilla%3F demonstrates that this restriction can be disabled by the user via `about:addons` for add-ons which opt-in.

This might explain why this doesn't appear to work in PDFs.

**Comment by ichaoX** [comment]
Highlighting should have basic support, like: [pdf](https://mozilla.github.io/pdf.js/legacy/web/compressed.tracemonkey-pldi-09.pdf#:~:text=dynamic%20compiler%20for-,JavaScript,-based%20on%20our).

However, copying doesn't work due to [tabs.executeScript()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript#:~:text=view%2C%20view%2Dsource%2C%20and-,PDF%20viewer,-pages.), and I'm unsure if there are other solutions.

If permission issues can be resolved, the effect should still be acceptable (unless PDF loading exceeds 5 seconds, the extension will abandon the search), like: [pdf.js](https://mozilla.github.io/pdf.js/legacy/web/viewer.html#:~:text=dynamic%20compiler%20for-,JavaScript,-based%20on%20our).

Currently, a possible solution would be to embed a PDF viewer within this extension, but I believe this feature exceeds the scope of this extension.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ichaoX/ext-textFragment/issues/5#issuecomment-2217746215

@ichaoX, https://mozilla.github.io/pdf.js/legacy/web/compressed.tracemonkey-pldi-09.pdf#:~:text=dynamic%20compiler%20for-,JavaScript,-based%20on%20our doesn't work for me. Should the extension automatically highlight the selected text after the PDF is downloaded?

1.	> ![Screenshot_20240709_143242](https://github.com/ichaoX/ext-textFragment/assets/42837531/cd0c08a9-557f-45eb-8efe-72d4fb41bae7)
1.	> ![Screencast_20240612_170920.webm](https://github.com/ichaoX/ext-textFragment/assets/42837531/c3fe5e15-c1fa-4936-b2e2-e0df8cb47404)

**Comment by ichaoX** [comment]
> Should the extension automatically highlight the selected text after the PDF is downloaded?

My preferences are set to default to opening PDFs using the browser's built-in PDF viewer, while this extension uses the [Find API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/find) for highlighting.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ichaoX/ext-textFragment/issues/5#issuecomment-2217854576

@ichaoX, could you show a screencast of how you do it?

**Comment by ichaoX** [comment]
![image](https://github.com/ichaoX/ext-textFragment/assets/11764590/ebe7a32f-86ef-4d16-b37e-2a3748275847)

Alternatively, you can try appending `#:~:text=*` to the `file:///*.pdf`.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ichaoX/ext-textFragment/issues/5#issuecomment-2218160430

@ichaoX, how do you generate that fragment without it functioning, though? Is it enough to copy some of the file content and put it through https://meyerweb.com/eric/tools/dencoder/ and append it to `#:~:text=`?

**Comment by ichaoX** [comment]
> @ichaoX, how do you generate that fragment without the extension functioning, though? Is it enough to copy some of the file content and put it through https://meyerweb.com/eric/tools/dencoder/ and append it to `#:~:text=`?

There is currently no simple way to achieve this.

I'm unsure if there are other ways to write to the clipboard. Even if copying is done through additional steps, due to the lack of get context capabilities, features such as creating links and finding text fragments remain degraded.

**Comment by ichaoX** [comment]
Configuring `extensions.webextensions.restrictedDomains` in `about:config` does indeed allow this extension to work on domains such as `support.mozilla.org`. For `addons.mozilla.org`, you also need to set `privacy.resistFingerprinting.block_mozAddonManager` to `true`.

However, WebExtensions do not have the ability to directly configure these preferences.

**Comment by RokeJulianLockhart** [comment]
> However, WebExtensions do not have the ability to directly configure these preferences.

Then I'll close the issue. However, https://www.reddit.com/r/firefox/comments/1c4y2g6/comment/kzst0os/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button and https://support.mozilla.org/en-US/kb/quarantined-domains would appear to demonstrate otherwise.

**Comment by ichaoX** [comment]
> However, a screenshot from [this Reddit comment](https://www.reddit.com/r/firefox/comments/1c4y2g6/comment/kzst0os/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button):
> 
> > ![image](https://private-user-images.githubusercontent.com/42837531/367319802-37383c45-1012-4bc8-8d07-c1693a123c1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzkxMjksIm5iZiI6MTcyNjIzODgyOSwicGF0aCI6Ii80MjgzNzUzMS8zNjczMTk4MDItMzczODNjNDUtMTAxMi00YmM4LThkMDctYzE2OTNhMTIzYzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE0NDcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NDA0YmEyNTdiODBmYTczMzRiZTQ5ZmNkMDg4YWNiYzdkNjg2YTMwYzIzM2I4YWExZjA5YTA2MDEwNTM2ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Q1SdeocRAhGZ3AHLY9nBYfwy6inys5DvoFuHxbd-7w)

The options in the screenshot can only remove the additional restrictions that "DARK READER" actively imposes on certain pages.

The relevant code locations are as follows:

https://github.com/darkreader/darkreader/blob/185c3eb4891a3a1f8665717f1cedd91d1da51917/src/utils/url.ts#L308-L314
https://github.com/darkreader/darkreader/blob/185c3eb4891a3a1f8665717f1cedd91d1da51917/src/background/extension.ts#L649-L656
https://github.com/darkreader/darkreader/blob/185c3eb4891a3a1f8665717f1cedd91d1da51917/src/background/utils/extension-api.ts#L5-L20

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ichaoX/ext-textFragment/issues/5#issuecomment-2349163779

@ichaoX, apologies if so, but did you see https://support.mozilla.org/en-US/kb/quarantined-domains, which I cited before? I think I've accidentally been referring to the wrong preference.

**Comment by ichaoX** [comment]
The impact of `extensions.quarantinedDomains.*` might be broader than `extensions.webextensions.restrictedDomains`. 

If you believe you are affected, please provide the steps to reproduce.
