### ISSUE TITLE
Doesn't function at specific URI.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ichaoX/ext-textFragment#9]
(For https://community.frame.work/t/touchpad-doesnt-function-on-fedora-40/58556/10?u=rokejulianlockhart) I try to utilize the extension by selecting the undermentioned content:

<blockQuote>

On systems with only a single OS installed, the grub menu's only function is to allow booting older kernels, which is only necessary as a rescue option in case of a severe kernel bug and as such not something which is directly useful for normal use.

Fedora already has a lot of work done to not show too technical boot messages to end users during bootup, e.g. we pass quiet to the kernel and we've plymouth to show a bootsplash instead of a bunch of "Starting service-foo: OK" messages.

The grub menu with its kernel versions is another example of showing too technical info to end-users and on non multi-boot systems it normally is not necessary, so it is better to hide it.

This change will add menu-auto-hide functionality to grub, which when enabled will hide the menu if:

1. The machine only has a single OS installed; and
2. The previous boot has set a flag to indicate it successfully booted

</blockQuote>

...from https://fedoraproject.org/w/index.php?title=Changes/HiddenGrubMenu&oldid=617602#Detailed_Description, yet nothing occurs.

**Comment by ichaoX** [comment]
Can this link `https://community.frame.work/t/touchpad-doesnt-function-on-fedora-40/58556/9?u=rokejulianlockhart#:~:text=On%20systems%20with,it%20successfully%20booted` be generated?

What version is your browser? I found that native features do not work stably in your case.

Please check if there is a `natively supported` prompt on the extension preferences page. If so, please try to uncheck `Disable this extension feature when natively supported` or disable `dom.text_fragments.enabled` on the `about:config` page.

**Comment by RokeJulianLockhart** [comment]
@ichaoX, apologies for the wait.

1.	> Can this link https://community.frame.work/t/touchpad-doesnt-function-on-fedora-40/58556/9?u=rokejulianlockhart#:~:text=On%20systems%20with,it%20successfully%20booted be generated?

	Yes:
	
	![Screenshot_20241015_213610](https://github.com/user-attachments/assets/1a568b23-33c9-444a-b3cf-cc3a184fdc3b)

1.	> What version is your browser? I found that native features do not work stably in your case.

	Indeed, they appear to fail for me more frequently than other users (unless most don't report their issues). Irrespective, I'm using https://fedora.pkgs.org/40/fedora-updates-x86_64/firefox-131.0.2-1.fc40.x86_64.rpm.html.

1.	> Please check if there is a natively supported prompt on the extension preferences page. If so, please try to uncheck "Disable this extension feature when natively supported", or disable `dom.text_fragments.enabled` on the `about:config` page.

	`dom.text_fragments.enabled` was `true` by default. Switching it to `false` and retrying didn't get it to work, though:

	https://github.com/user-attachments/assets/ffa7f6a5-26fb-4ca6-af7b-a8352883e83e

**Comment by ichaoX** [comment]
Thank you for your report. I can reproduce this issue and will fix it in the next version.

This bug is caused by the `🔗` in the context being incorrectly split into two invalid characters.

**Comment by RokeJulianLockhart** [comment]
> Additionally, Firefox v132 does not natively support [this link](https://fedoraproject.org/w/index.php?title=Changes/HiddenGrubMenu&oldid=617602#Detailed_Description:~:text=%F0%9F%94%97%20Detailed%20Description-,On%20systems%20with,it%20successfully%20booted,-To%20make%20the), which should be a bug in Firefox.

@ichaoX, I don't mind filing a bug for that, but I don't think I'd be much use in answering Mozilla's follow-up questions.
